from classes.models.GameState import Products

products = [
    Products(
        name="Yellow Wrapped",
        img="wrappedsolid_yellow.png",
        base_cost=100,
        base_time=5,
        factory_number=1,
    ),
    Products(
        name="Red Wrapped",
        img="wrappedsolid_red.png",
        base_cost=100,
        base_time=5,
        factory_number=1,
    ),
    Products(
        name="Teal Star",
        img="star_teal.png",
        base_cost=600,
        base_time=7,
        factory_number=2,
    ),
    Products(
        name="Orange Star",
        img="star_orange.png",
        base_cost=600,
        base_time=7,
        factory_number=2,
    ),
    Products(
        name="Orange MM",
        img="mm_orange.png",
        base_cost=1200,
        base_time=9,
        factory_number=3,
    ),
    Products(
        name="Brown MM",
        img="mm_brown.png",
        base_cost=1200,
        base_time=9,
        factory_number=3,
    ),
    Products(
        name="Green Jelly",
        img="jelly_green.png",
        base_cost=2000,
        base_time=11,
        factory_number=4,
    ),
    Products(
        name="Blue Jelly",
        img="jelly_blue.png",
        base_cost=2000,
        base_time=11,
        factory_number=4,
    ),
    Products(
        name="Orange Heart",
        img="heart_orange.png",
        base_cost=3500,
        base_time=12,
        factory_number=5,
    ),
    Products(
        name="Green Heart",
        img="heart_green.png",
        base_cost=3500,
        base_time=12,
        factory_number=5,
    ),
    Products(
        name="Red Big Jelly",
        img="jellybig_red.png",
        base_cost=4500,
        base_time=14,
        factory_number=6,
    ),
    Products(
        name="Yellow Big Jelly",
        img="jellybig_yellow.png",
        base_cost=4500,
        base_time=14,
        factory_number=6,
    ),
    Products(
        name="Purple Lollipop",
        img="lollipop_purple.png",
        base_cost=6000,
        base_time=16,
        factory_number=7,
    ),
    Products(
        name="Rainbow Lollipop",
        img="lollipop_rainbow.png",
        base_cost=6000,
        base_time=16,
        factory_number=7,
    ),
    Products(
        name="Candy Corn",
        img="candycorn.png",
        base_cost=8000,
        base_time=18,
        factory_number=8,
    ),
    Products(
        name="Candy Cane",
        img="candycane.png",
        base_cost=8000,
        base_time=18,
        factory_number=8,
    ),
    Products(
        name="Blue Bean",
        img="bean_blue.png",
        base_cost=10000,
        base_time=20,
        factory_number=9,
    ),
    Products(
        name="Orange Bean",
        img="bean_orange.png",
        base_cost=10000,
        base_time=20,
        factory_number=9,
    ),
    Products(
        name="Candy Humbug",
        img="candyhumbug.png",
        base_cost=10000,
        base_time=20,
        factory_number=9,
    ),
]
